### ISSUE TITLE
Create contracts

### ISSUE THREAD

**Issue by lkngtn** [1Hive/redemptions#1]
The requirements would be pretty simple:

1. The app would be initialized with a `vault` address and a `minime token` address 
2. The app should maintain a list of tokens
3. Users could burn any amount of `minime token` and be transferred a proportional amount of the balances of token in the lis that are stored in the `vault`. 

For example if there are a total of 100 Merit tokens in the supply, and I "redeem" 10, I would be transferred 10% of the balance in the vault of each token in the list. 

For simplicity, we can limit the scope to only track a single vault asset.

**Comment by lkngtn** [comment]
The redemption function should be protected by a `role` so that an organization can restrict redemptions using Aragon Permissions.

**Comment by 0xGabi** [comment]
Close on #3

**Comment by 0xGabi** [comment]
Close on #3

**Comment by 0xGabi** [comment]
Reopen cause I forgot we have it on the project app 😅

**Comment by lkngtn** [comment]
This was completed and paid out! Thanks everyone who contributed to our first full test of the projects app!
